runtime: python39
entrypoint: gunicorn -b :$PORT main:app

instance_class: F2

env_variables:
  ENV_VAR_NAME: VALUE

handlers:
- url: /static
  static_dir: MSite/static/

- url: /static/css
  static_dir: MSite/static/css

- url: /static/images
  static_dir: MSite/static/images

#required for SSL
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto